//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teference.Zoho.Api.Internals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teference.Zoho.Api.Internals.ApiResources", typeof(ApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsDeleteAddon {
            get {
                return ResourceManager.GetString("ZsDeleteAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/cards/{1}.
        /// </summary>
        internal static string ZsDeleteCard {
            get {
                return ResourceManager.GetString("ZsDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/contactpersons/{1}.
        /// </summary>
        internal static string ZsDeleteContactPerson {
            get {
                return ResourceManager.GetString("ZsDeleteContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsDeleteCoupon {
            get {
                return ResourceManager.GetString("ZsDeleteCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsDeleteCustomer {
            get {
                return ResourceManager.GetString("ZsDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsDeletePlan {
            get {
                return ResourceManager.GetString("ZsDeletePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsDeleteProduct {
            get {
                return ResourceManager.GetString("ZsDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}.
        /// </summary>
        internal static string ZsDeleteSubscription {
            get {
                return ResourceManager.GetString("ZsDeleteSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/notes/{1}.
        /// </summary>
        internal static string ZsDeleteSubscriptionDeleteNote {
            get {
                return ResourceManager.GetString("ZsDeleteSubscriptionDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/coupons.
        /// </summary>
        internal static string ZsDeleteSubscriptionRemoveCoupon {
            get {
                return ResourceManager.GetString("ZsDeleteSubscriptionRemoveCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsGetAddon {
            get {
                return ResourceManager.GetString("ZsGetAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons.
        /// </summary>
        internal static string ZsGetAddonsAll {
            get {
                return ResourceManager.GetString("ZsGetAddonsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/cards/{1}.
        /// </summary>
        internal static string ZsGetCard {
            get {
                return ResourceManager.GetString("ZsGetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/contactpersons/{1}.
        /// </summary>
        internal static string ZsGetContactPerson {
            get {
                return ResourceManager.GetString("ZsGetContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/contactpersons.
        /// </summary>
        internal static string ZsGetContactPersonsAll {
            get {
                return ResourceManager.GetString("ZsGetContactPersonsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsGetCoupon {
            get {
                return ResourceManager.GetString("ZsGetCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons.
        /// </summary>
        internal static string ZsGetCouponsAll {
            get {
                return ResourceManager.GetString("ZsGetCouponsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsGetCustomer {
            get {
                return ResourceManager.GetString("ZsGetCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        internal static string ZsGetCustomersAll {
            get {
                return ResourceManager.GetString("ZsGetCustomersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages.
        /// </summary>
        internal static string ZsGetHostedPageAll {
            get {
                return ResourceManager.GetString("ZsGetHostedPageAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages/{0}.
        /// </summary>
        internal static string ZsGetHostedPlan {
            get {
                return ResourceManager.GetString("ZsGetHostedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}.
        /// </summary>
        internal static string ZsGetInvoice {
            get {
                return ResourceManager.GetString("ZsGetInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}.
        /// </summary>
        internal static string ZsGetInvoiceAsPdf {
            get {
                return ResourceManager.GetString("ZsGetInvoiceAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices.
        /// </summary>
        internal static string ZsGetInvoicesAll {
            get {
                return ResourceManager.GetString("ZsGetInvoicesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices?customer_id={0}.
        /// </summary>
        internal static string ZsGetInvoicesAllByCustomerId {
            get {
                return ResourceManager.GetString("ZsGetInvoicesAllByCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices?subscription_id={0}.
        /// </summary>
        internal static string ZsGetInvoicesAllBySubscriptionId {
            get {
                return ResourceManager.GetString("ZsGetInvoicesAllBySubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsGetPlan {
            get {
                return ResourceManager.GetString("ZsGetPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        internal static string ZsGetPlansAll {
            get {
                return ResourceManager.GetString("ZsGetPlansAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsGetProduct {
            get {
                return ResourceManager.GetString("ZsGetProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string ZsGetProductsAll {
            get {
                return ResourceManager.GetString("ZsGetProductsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}.
        /// </summary>
        internal static string ZsGetSubscription {
            get {
                return ResourceManager.GetString("ZsGetSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions.
        /// </summary>
        internal static string ZsGetSubscriptionsAll {
            get {
                return ResourceManager.GetString("ZsGetSubscriptionsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons.
        /// </summary>
        internal static string ZsPostAddon {
            get {
                return ResourceManager.GetString("ZsPostAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}/markasactive.
        /// </summary>
        internal static string ZsPostAddonMarkActive {
            get {
                return ResourceManager.GetString("ZsPostAddonMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostAddonMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostAddonMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/cards.
        /// </summary>
        internal static string ZsPostCard {
            get {
                return ResourceManager.GetString("ZsPostCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/contactpersons.
        /// </summary>
        internal static string ZsPostContactPerson {
            get {
                return ResourceManager.GetString("ZsPostContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons.
        /// </summary>
        internal static string ZsPostCoupon {
            get {
                return ResourceManager.GetString("ZsPostCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}/markasactive.
        /// </summary>
        internal static string ZsPostCouponMarkActive {
            get {
                return ResourceManager.GetString("ZsPostCouponMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostCouponMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostCouponMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        internal static string ZsPostCustomer {
            get {
                return ResourceManager.GetString("ZsPostCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages/buyonetimeaddon.
        /// </summary>
        internal static string ZsPostHostedPageBuyAddon {
            get {
                return ResourceManager.GetString("ZsPostHostedPageBuyAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages/newsubscription.
        /// </summary>
        internal static string ZsPostHostedPageCreateSubscription {
            get {
                return ResourceManager.GetString("ZsPostHostedPageCreateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages/updatecard.
        /// </summary>
        internal static string ZsPostHostedPageUpdateCard {
            get {
                return ResourceManager.GetString("ZsPostHostedPageUpdateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hostedpages/updatesubscription.
        /// </summary>
        internal static string ZsPostHostedPageUpdateSubscription {
            get {
                return ResourceManager.GetString("ZsPostHostedPageUpdateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}/cancelwriteoff.
        /// </summary>
        internal static string ZsPostInvoiceCancelWriteOff {
            get {
                return ResourceManager.GetString("ZsPostInvoiceCancelWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}/collect.
        /// </summary>
        internal static string ZsPostInvoiceCollectCharges {
            get {
                return ResourceManager.GetString("ZsPostInvoiceCollectCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}/convertoopen.
        /// </summary>
        internal static string ZsPostInvoiceConvertToOpen {
            get {
                return ResourceManager.GetString("ZsPostInvoiceConvertToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{invoice_id}/void.
        /// </summary>
        internal static string ZsPostInvoiceConvertToVoid {
            get {
                return ResourceManager.GetString("ZsPostInvoiceConvertToVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}/email.
        /// </summary>
        internal static string ZsPostInvoiceEmail {
            get {
                return ResourceManager.GetString("ZsPostInvoiceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoices/{0}/writeoff.
        /// </summary>
        internal static string ZsPostInvoiceWriteOff {
            get {
                return ResourceManager.GetString("ZsPostInvoiceWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        internal static string ZsPostPlan {
            get {
                return ResourceManager.GetString("ZsPostPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}/markasactive.
        /// </summary>
        internal static string ZsPostPlanMarkActive {
            get {
                return ResourceManager.GetString("ZsPostPlanMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostPlanMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostPlanMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string ZsPostProduct {
            get {
                return ResourceManager.GetString("ZsPostProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}/markasactive.
        /// </summary>
        internal static string ZsPostProductMarkActive {
            get {
                return ResourceManager.GetString("ZsPostProductMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostProductMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostProductMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions.
        /// </summary>
        internal static string ZsPostSubscription {
            get {
                return ResourceManager.GetString("ZsPostSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/charge.
        /// </summary>
        internal static string ZsPostSubscriptionAddCharge {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionAddCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/contactpersons.
        /// </summary>
        internal static string ZsPostSubscriptionAddContactPerson {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionAddContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/notes.
        /// </summary>
        internal static string ZsPostSubscriptionAddNote {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/coupons/{1}.
        /// </summary>
        internal static string ZsPostSubscriptionAssociateCoupon {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionAssociateCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/autocollect.
        /// </summary>
        internal static string ZsPostSubscriptionAutoCollect {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionAutoCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/cancel?cancel_at_end={1}.
        /// </summary>
        internal static string ZsPostSubscriptionCancel {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/postpone.
        /// </summary>
        internal static string ZsPostSubscriptionPostponeRenewal {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionPostponeRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}/reactivate.
        /// </summary>
        internal static string ZsPostSubscriptionReactivate {
            get {
                return ResourceManager.GetString("ZsPostSubscriptionReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsPutAddon {
            get {
                return ResourceManager.GetString("ZsPutAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/cards/{1}.
        /// </summary>
        internal static string ZsPutCard {
            get {
                return ResourceManager.GetString("ZsPutCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}/contactpersons/{1}.
        /// </summary>
        internal static string ZsPutContactPerson {
            get {
                return ResourceManager.GetString("ZsPutContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsPutCoupon {
            get {
                return ResourceManager.GetString("ZsPutCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsPutCustomer {
            get {
                return ResourceManager.GetString("ZsPutCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsPutPlan {
            get {
                return ResourceManager.GetString("ZsPutPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsPutProduct {
            get {
                return ResourceManager.GetString("ZsPutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions/{0}.
        /// </summary>
        internal static string ZsPutSubscription {
            get {
                return ResourceManager.GetString("ZsPutSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://subscriptions.zoho.com/api/v1/.
        /// </summary>
        internal static string ZsRootEndpoint {
            get {
                return ResourceManager.GetString("ZsRootEndpoint", resourceCulture);
            }
        }
    }
}
