//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teference.Zoho.Api.Internals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teference.Zoho.Api.Internals.ApiResources", typeof(ApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsDeleteAddon {
            get {
                return ResourceManager.GetString("ZsDeleteAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsDeleteCoupon {
            get {
                return ResourceManager.GetString("ZsDeleteCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsDeleteCustomer {
            get {
                return ResourceManager.GetString("ZsDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsDeletePlan {
            get {
                return ResourceManager.GetString("ZsDeletePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsDeleteProduct {
            get {
                return ResourceManager.GetString("ZsDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsGetAddon {
            get {
                return ResourceManager.GetString("ZsGetAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons.
        /// </summary>
        internal static string ZsGetAddonsAll {
            get {
                return ResourceManager.GetString("ZsGetAddonsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsGetCoupon {
            get {
                return ResourceManager.GetString("ZsGetCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons.
        /// </summary>
        internal static string ZsGetCouponsAll {
            get {
                return ResourceManager.GetString("ZsGetCouponsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsGetCustomer {
            get {
                return ResourceManager.GetString("ZsGetCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        internal static string ZsGetCustomersAll {
            get {
                return ResourceManager.GetString("ZsGetCustomersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsGetPlan {
            get {
                return ResourceManager.GetString("ZsGetPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        internal static string ZsGetPlansAll {
            get {
                return ResourceManager.GetString("ZsGetPlansAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsGetProduct {
            get {
                return ResourceManager.GetString("ZsGetProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string ZsGetProductsAll {
            get {
                return ResourceManager.GetString("ZsGetProductsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons.
        /// </summary>
        internal static string ZsPostAddon {
            get {
                return ResourceManager.GetString("ZsPostAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}/markasactive.
        /// </summary>
        internal static string ZsPostAddonMarkActive {
            get {
                return ResourceManager.GetString("ZsPostAddonMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostAddonMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostAddonMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons.
        /// </summary>
        internal static string ZsPostCoupon {
            get {
                return ResourceManager.GetString("ZsPostCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}/markasactive.
        /// </summary>
        internal static string ZsPostCouponMarkActive {
            get {
                return ResourceManager.GetString("ZsPostCouponMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostCouponMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostCouponMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        internal static string ZsPostCustomer {
            get {
                return ResourceManager.GetString("ZsPostCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans.
        /// </summary>
        internal static string ZsPostPlan {
            get {
                return ResourceManager.GetString("ZsPostPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}/markasactive.
        /// </summary>
        internal static string ZsPostPlanMarkActive {
            get {
                return ResourceManager.GetString("ZsPostPlanMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostPlanMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostPlanMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string ZsPostProduct {
            get {
                return ResourceManager.GetString("ZsPostProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}/markasactive.
        /// </summary>
        internal static string ZsPostProductMarkActive {
            get {
                return ResourceManager.GetString("ZsPostProductMarkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}/markasinactive.
        /// </summary>
        internal static string ZsPostProductMarkInActive {
            get {
                return ResourceManager.GetString("ZsPostProductMarkInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addons/{0}.
        /// </summary>
        internal static string ZsPutAddon {
            get {
                return ResourceManager.GetString("ZsPutAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupons/{0}.
        /// </summary>
        internal static string ZsPutCoupon {
            get {
                return ResourceManager.GetString("ZsPutCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers/{0}.
        /// </summary>
        internal static string ZsPutCustomer {
            get {
                return ResourceManager.GetString("ZsPutCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plans/{0}.
        /// </summary>
        internal static string ZsPutPlan {
            get {
                return ResourceManager.GetString("ZsPutPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products/{0}.
        /// </summary>
        internal static string ZsPutProduct {
            get {
                return ResourceManager.GetString("ZsPutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://subscriptions.zoho.com/api/v1/.
        /// </summary>
        internal static string ZsRootEndpoint {
            get {
                return ResourceManager.GetString("ZsRootEndpoint", resourceCulture);
            }
        }
    }
}
